### PR TITLE
Add additional build scripts

### PR DESCRIPTION
**Pull request by RealFX-Code**

### CODE REVIEW

**Comment by cat658011** [comment]
Im ready to apply last commit(Ignore finished builds) but why additional scripts?

**Comment by cat658011** [comment]
Also tbh scripts shit

**Comment by RealFX-Code** [comment]
> Im ready to apply last commit(Ignore finished builds) but why additional scripts?
> 

To make it easier to both get started with development and build for multiple devices

**Comment by cat658011** [comment]
useless sir

**Comment by cat658011** [comment]
No

**Pull request closed without merging**
